import { argbFromHex, themeFromSourceColor, hexFromArgb } from "@material/material-color-utilities";
import * as fs from 'fs';
import * as path from 'path';

// Function to convert ARGB to hex
function argbToHex(argb: number): string {
  return hexFromArgb(argb);
}

// Function to generate palette structure similar to _theme-colors.scss
function generatePaletteStructure(theme: any) {
  const tones = [0, 10, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100];
  
  const palettes: any = {};
  
  // Generate primary palette
  palettes.primary = {};
  tones.forEach(tone => {
    palettes.primary[tone] = argbToHex(theme.palettes.primary.tone(tone));
  });
  
  // Generate secondary palette
  palettes.secondary = {};
  tones.forEach(tone => {
    palettes.secondary[tone] = argbToHex(theme.palettes.secondary.tone(tone));
  });
  
  // Generate tertiary palette
  palettes.tertiary = {};
  tones.forEach(tone => {
    palettes.tertiary[tone] = argbToHex(theme.palettes.tertiary.tone(tone));
  });
  
  // Generate neutral palette
  palettes.neutral = {};
  const neutralTones = [...tones, 4, 6, 12, 17, 22, 24, 87, 92, 94, 96];
  neutralTones.sort((a, b) => a - b);
  neutralTones.forEach(tone => {
    palettes.neutral[tone] = argbToHex(theme.palettes.neutral.tone(tone));
  });
  
  // Generate neutral-variant palette
  palettes['neutral-variant'] = {};
  tones.forEach(tone => {
    palettes['neutral-variant'][tone] = argbToHex(theme.palettes.neutralVariant.tone(tone));
  });
  
  // Generate error palette
  palettes.error = {};
  tones.forEach(tone => {
    palettes.error[tone] = argbToHex(theme.palettes.error.tone(tone));
  });
  
  return palettes;
}

// Function to generate SCSS-like output
function generateScssOutput(palettes: any, sourceColor: string) {
  let scss = `// This file was generated by running gen-mat-colors.ts
// Proceed with caution if making changes to this file.

@use 'sass:map';
@use '@angular/material' as mat;

// Note: Color palettes are generated from primary: ${sourceColor}
$_palettes: (
`;

  // Generate each palette
  Object.keys(palettes).forEach((paletteName, index) => {
    scss += `  ${paletteName}: (\n`;
    const palette = palettes[paletteName];
    const toneKeys = Object.keys(palette).map(Number).sort((a, b) => a - b);
    
    toneKeys.forEach((tone, toneIndex) => {
      const isLast = toneIndex === toneKeys.length - 1;
      scss += `    ${tone}: ${palette[tone]}${isLast ? '' : ','}\n`;
    });
    
    const isLastPalette = index === Object.keys(palettes).length - 1;
    scss += `  )${isLastPalette ? '' : ','}\n`;
  });

  scss += `);\n\n`;
  
  // Generate the rest structure
  scss += `$_rest: (
  secondary: map.get($_palettes, secondary),
  neutral: map.get($_palettes, neutral),
  neutral-variant: map.get($_palettes,  neutral-variant),
  error: map.get($_palettes, error),
);

$primary-palette: map.merge(map.get($_palettes, primary), $_rest);
$tertiary-palette: map.merge(map.get($_palettes, tertiary), $_rest);
`;

  return scss;
}

// Get the theme from a hex color (using the same color as in _theme-colors.scss)
const sourceColor = '#ff7000';
const theme = themeFromSourceColor(argbFromHex(sourceColor));

// Generate the palette structure
const palettes = generatePaletteStructure(theme);

// Print out the palettes as JSON for debugging
console.log('Generated palettes:');
console.log(JSON.stringify(palettes, null, 2));

console.log('\n' + '='.repeat(80) + '\n');

// Generate and print SCSS output
const scssOutput = generateScssOutput(palettes, sourceColor);
console.log('SCSS Output:');
console.log(scssOutput);

// Write the SCSS output to file
const outputFilePath = path.join(__dirname, 'src', '_gen_theme_colors.scss');
fs.writeFileSync(outputFilePath, scssOutput, 'utf8');
console.log(`\nSCSS file written to: ${outputFilePath}`);

